language: php
sudo: required
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - nightly
  # fails with the message "HHVM nightly is no longer supported on Ubuntu Precise"
  #- hhvm-nightly

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
  allow_failures:
    - php: nightly
    - php: hhvm


before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install -o --no-interaction --prefer-source
  - mkdir -p build/logs
  - tests/bin/travis-init.sh
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar

before_script:
  # xdebug does not work with PHP 7.
 - if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then phpenv config-rm xdebug.ini; fi

script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then
      phpdbg -qrr vendor/phpunit/phpunit/phpunit --verbose --colors --coverage-clover=build/logs/clover.xml --coverage-text;
    else
      vendor/bin/phpunit --verbose --colors --coverage-clover build/logs/clover.xml --coverage-text;
    fi

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#ouarz"
  email:
    recipients:
      - dev-team@ouarz.net
    on_success: change
    on_failure: change

cache:
 directories:
   - $HOME/.composer/cache
